import 'package:flutter/material.dart';

class InterestsSelector extends StatelessWidget {
  final List<String> selectedInterests;
  final Function(List<String>) onInterestsChanged;
  final List<String> availableInterests;

  const InterestsSelector({
    super.key,
    required this.selectedInterests,
    required this.onInterestsChanged,
    this.availableInterests = const [
      'Musique',
      'Cinéma',
      'Lecture',
      'Sport',
      'Voyage',
      'Cuisine',
      'Art',
      'Photographie',
      'Danse',
      'Théâtre',
      'Mode',
      'Technologie',
      'Nature',
      'Animaux',
      'Jeux vidéo',
      'Yoga',
      'Méditation',
      'Histoire',
      'Science',
      'Politique',
      'Écologie',
      'Langues',
      'Bricolage',
      'Jardinage',
      'Automobile',
      'Moto',
      'Vélo',
      'Randonnée',
      'Escalade',
      'Natation',
      'Tennis',
      'Football',
      'Basketball',
      'Volleyball',
      'Golf',
      'Ski',
      'Surf',
      'Plongée',
      'Peinture',
      'Dessin',
      'Sculpture',
      'Architecture',
      'Design',
      'Mode',
      'Cosmétique',
      'Gastronomie',
      'Vin',
      'Café',
      'Thé',
      'Pâtisserie',
      'Boulangerie',
      'Chocolat',
      'Fromage',
      'Végétarisme',
      'Véganisme',
      'Bio',
      'Zéro déchet',
      'DIY',
      'Décoration',
      'Antiquités',
      'Collection',
      'Philatélie',
      'Numismatique',
      'Astronomie',
      'Météorologie',
      'Géologie',
      'Botanique',
      'Zoologie',
      'Ornithologie',
      'Entomologie',
      'Marine',
      'Aéronautique',
      'Espace',
      'Robotique',
      'Intelligence artificielle',
      'Programmation',
      'Mathématiques',
      'Physique',
      'Chimie',
      'Biologie',
      'Médecine',
      'Psychologie',
      'Philosophie',
      'Sociologie',
      'Anthropologie',
      'Archéologie',
      'Géographie',
      'Économie',
      'Finance',
      'Marketing',
      'Management',
      'Droit',
      'Journalisme',
      'Communication',
      'Publicité',
      'Relations publiques',
      'Éducation',
      'Enseignement',
      'Formation',
      'Coaching',
      'Mentorat',
      'Bénévolat',
      'Humanitaire',
      'Associatif',
      'Politique',
      'Écologie',
      'Développement durable',
      'Énergies renouvelables',
      'Recyclage',
      'Compostage',
      'Permaculture',
      'Agriculture',
      'Élevage',
      'Apiculture',
      'Viticulture',
      'Arboriculture',
      'Floriculture',
      'Pisciculture',
      'Mycologie',
      'Herboristerie',
      'Aromathérapie',
      'Phytothérapie',
      'Homéopathie',
      'Acupuncture',
      'Ostéopathie',
      'Chiropraxie',
      'Naturopathie',
      'Ayurvéda',
      'Médecine chinoise',
      'Médecine tibétaine',
      'Médecine traditionnelle',
      'Médecine moderne',
      'Médecine alternative',
      'Médecine douce',
      'Médecine préventive',
      'Médecine curative',
      'Médecine palliative',
      'Médecine esthétique',
      'Médecine sportive',
      'Médecine du travail',
      'Médecine scolaire',
      'Médecine universitaire',
      'Médecine hospitalière',
      'Médecine libérale',
      'Médecine sociale',
      'Médecine humanitaire',
      'Médecine militaire',
      'Médecine spatiale',
      'Médecine maritime',
      'Médecine aéronautique',
      'Médecine vétérinaire',
      'Médecine dentaire',
      'Médecine ophtalmologique',
      'Médecine ORL',
      'Médecine cardiologique',
      'Médecine pulmonaire',
      'Médecine digestive',
      'Médecine hépatique',
      'Médecine rénale',
      'Médecine urologique',
      'Médecine gynécologique',
      'Médecine obstétricale',
      'Médecine pédiatrique',
      'Médecine gériatrique',
      'Médecine psychiatrique',
      'Médecine neurologique',
      'Médecine dermatologique',
      'Médecine endocrinologique',
      'Médecine immunologique',
      'Médecine infectieuse',
      'Médecine tropicale',
      'Médecine du voyage',
      'Médecine du sport',
      'Médecine du travail',
      'Médecine scolaire',
      'Médecine universitaire',
      'Médecine hospitalière',
      'Médecine libérale',
      'Médecine sociale',
      'Médecine humanitaire',
      'Médecine militaire',
      'Médecine spatiale',
      'Médecine maritime',
      'Médecine aéronautique',
      'Médecine vétérinaire',
      'Médecine dentaire',
      'Médecine ophtalmologique',
      'Médecine ORL',
      'Médecine cardiologique',
      'Médecine pulmonaire',
      'Médecine digestive',
      'Médecine hépatique',
      'Médecine rénale',
      'Médecine urologique',
      'Médecine gynécologique',
      'Médecine obstétricale',
      'Médecine pédiatrique',
      'Médecine gériatrique',
      'Médecine psychiatrique',
      'Médecine neurologique',
      'Médecine dermatologique',
      'Médecine endocrinologique',
      'Médecine immunologique',
      'Médecine infectieuse',
      'Médecine tropicale',
      'Médecine du voyage',
    ],
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Intérêts (max 10)',
          style: TextStyle(fontSize: 16),
        ),
        const SizedBox(height: 8),
        Container(
          decoration: BoxDecoration(
            border: Border.all(color: Colors.grey),
            borderRadius: BorderRadius.circular(4),
          ),
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Wrap(
              spacing: 8.0,
              runSpacing: 4.0,
              children: availableInterests.map((interest) {
                return FilterChip(
                  label: Text(interest),
                  selected: selectedInterests.contains(interest),
                  onSelected: (bool selected) {
                    List<String> newInterests = List.from(selectedInterests);
                    if (selected && newInterests.length < 10) {
                      newInterests.add(interest);
                    } else if (!selected) {
                      newInterests.remove(interest);
                    }
                    onInterestsChanged(newInterests);
                  },
                  showCheckmark: true,
                  backgroundColor: Colors.grey[200],
                  selectedColor:
                      Theme.of(context).primaryColor.withOpacity(0.2),
                  labelStyle: TextStyle(
                    color: selectedInterests.contains(interest)
                        ? Theme.of(context).primaryColor
                        : Colors.black87,
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ],
    );
  }
}
