// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11XZZ3_qwL22YhwZNNDpr2n0QeiRUrNk',
    appId: '1:649409676103:web:45e4167c947a17cd08c262',
    messagingSenderId: '649409676103',
    projectId: 'findlove-b8a98',
    authDomain: 'findlove-b8a98.firebaseapp.com',
    storageBucket: 'findlove-b8a98.firebasestorage.app',
    measurementId: 'G-BP6YS08R59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGkhvCl3QFF_wDRogjq8MsldvJYAS_bw',
    appId: '1:649409676103:android:744384fc1311193608c262',
    messagingSenderId: '649409676103',
    projectId: 'findlove-b8a98',
    storageBucket: 'findlove-b8a98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoNfVIaJRRusfglRaUf6fwdbOEzQ9sGaE',
    appId: '1:649409676103:ios:bfd3676612c2649f08c262',
    messagingSenderId: '649409676103',
    projectId: 'findlove-b8a98',
    storageBucket: 'findlove-b8a98.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoNfVIaJRRusfglRaUf6fwdbOEzQ9sGaE',
    appId: '1:649409676103:ios:bfd3676612c2649f08c262',
    messagingSenderId: '649409676103',
    projectId: 'findlove-b8a98',
    storageBucket: 'findlove-b8a98.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC11XZZ3_qwL22YhwZNNDpr2n0QeiRUrNk',
    appId: '1:649409676103:web:31495cacb478dc8608c262',
    messagingSenderId: '649409676103',
    projectId: 'findlove-b8a98',
    authDomain: 'findlove-b8a98.firebaseapp.com',
    storageBucket: 'findlove-b8a98.firebasestorage.app',
    measurementId: 'G-LDDGJLTRDK',
  );

}